server:
  port: 9991

spring:
  application:
    name: customer-service
  data:
    mongodb:
      username: root
      password: Vaishv@123
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
